### ISSUE TITLE
后台页面显示异常

### ISSUE THREAD

**Issue by ohacn** [maccmspro/maccms_pro#1]
全新安装，能登录后台，但是点击每个菜单，页面都只会转圈圈，打不开页面，后台除了菜单显示，所有页面点击都是空白。

好像是后台欢迎页面的问题，欢迎页面报错“Out of memory (allocated 880803840) (tried to allocate 402653192 bytes)”，等欢迎页面卡死之后弹出以上信息，然后其他页面就也能正常打开了。

**Comment by maccmspro** [comment]
感谢反馈，您服务器是什么系统？我们排查下。

**Comment by ohacn** [comment]
> 感谢反馈，您服务器是什么系统？我们排查下。

windows 10，用IIS或者apache都这样，内存溢出。

打开前台正常，打开后台登录页面正常，但是输入密码登录后，PHP疯狂占用CPU并且内存暴增，然后进程崩溃后，才能正常打开后台其他页面。但是点欢迎页还是一样，CPU和内存暴增。

**Comment by maccmspro** [comment]
目前在windows下未重现到相关错误，是否方便贴一下php日志，看看能否定位到具体报错位置。  
PS: 可以开启一下网站根目录下.env的这2个选项：
```
app_debug=true
app_trace=true
```

**Comment by ohacn** [comment]
我看其他人也碰到同样的问题，程序bug吧。
系统用的windows10，护卫神Apache一键环境。

**Comment by maccmspro** [comment]
好，我们再排查下。

**Comment by maccmspro** [comment]
已修复一版 可以下载新包使用
