### ISSUE TITLE
定时任务测试出错

### ISSUE THREAD

**Issue by holyboy79** [maccmspro/maccms_pro#10]
显示 ERR_INCOMPLETE_CHUNKED_ENCODING

**Comment by maccmspro** [comment]
能否截图看看具体哪里报错

**Comment by holyboy79** [comment]
------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "maccmspro/maccms_pro"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年1月23日(星期天) 晚上11:16
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [maccmspro/maccms_pro] 定时任务测试出错 (Issue #10)





 
能否截图看看具体哪里报错
 
&nbsp;(request: "GET /api.php?s=/timming/index.html&amp;enforce=1&amp;name=02") executing too slow (37.020778 sec), logging

[24-Jan-2022 00:49:02] NOTICE: child 13641 stopped for tracing

[24-Jan-2022 00:49:02] NOTICE: about to trace 13641

[24-Jan-2022 00:49:02] NOTICE: finished trace of 13641

错误日志

**Comment by maccmspro** [comment]
是不是有较多的采集任务 如果vod表数据量大、采集开了自动下载图片和生成标签 会比较慢 这块我们后面优化下
