### ISSUE TITLE
install安装的时候数据库前缀改了之后，安装成功数据库报错

### ISSUE THREAD

**Issue by lkzwc** [maccmspro/maccms_pro#3]
![image](https://user-images.githubusercontent.com/84896877/147852167-6a2a522a-a3c0-4eb3-8a99-e99bd4d9dd2c.png)
前缀名称没有替换过来

**Comment by maccmspro** [comment]
请在服务器网站根目录的.env里将配置项database_table_prefix设置为修改后的值。
