### ISSUE TITLE
用Linux系统后台空白

### ISSUE THREAD

**Issue by seek2024** [maccmspro/maccms_pro#4]
![Screenshot_2022_0103_175328](https://user-images.githubusercontent.com/62018857/147917786-64eab16b-6ad7-4c48-8c2f-3e7963b810af.jpg)

**Comment by seek2024** [comment]
前台能访问,后台一片空白，是不是数据库问题!
![Screenshot_2022_0103_175616](https://user-images.githubusercontent.com/62018857/147918036-dc6e98d3-99f9-4383-b5dd-0e775b849419.jpg)
![Uploading Screenshot_2022_0103_175616.jpg…]()

**Comment by seek2024** [comment]
程序需要更新一下，吃cpu厉害

**Comment by seek2024** [comment]
后台页面空白

**Comment by ohacn** [comment]
我跟你的一样的问题，后台狂吃CPU

**Comment by seek2024** [comment]
> 

我一般用Linux

**Comment by maccmspro** [comment]
已修复一版 麻烦用新的安装包再次尝试

**Comment by seek2024** [comment]
> 

好的！

**Comment by seek2024** [comment]
![Uploading Screenshot_20220106_120945.jpg…]()
自定义资源查询不了

**Comment by qmkj999** [comment]
![Uploading Screenshot_20220106_120945.jpg…]()

**Comment by qmkj999** [comment]
![Uploading Screenshot_2022_0106_120835.jpg…]()

**Comment by seek2024** [comment]
后台采集不稳定

**Comment by maccmspro** [comment]
上面的图片看不到
采集不稳定一般受服务器到采集目标站的网络连通性影响 如果开了采集图片和自动生成tag 先关一下试试

**Comment by seek2024** [comment]
可以用了
