### ISSUE TITLE
自定义采集影视搜索不到

### ISSUE THREAD

**Issue by seek2024** [maccmspro/maccms_pro#5]
自定义采集影视搜索不到
![Screenshot_2022_0108_121323](https://user-images.githubusercontent.com/62018857/148631015-13f8b365-384c-4bae-ad4f-58b841e7146d.jpg)

**Comment by maccmspro** [comment]
提供一下重现步骤

**Comment by seek2024** [comment]
自定义采集资源后台采集页搜索错误

**Comment by maccmspro** [comment]
已定位到问题 下个版本解决
