### ISSUE TITLE
安装后首页报错

### ISSUE THREAD

**Issue by KormiMeiko** [maccmspro/maccms_pro#6]
全新安装
首页打开显示
SQLSTATE[42S02]: Base table or view not found: 1146 Table 'animiwa.mac_type' doesn't exist

**Comment by seek2024** [comment]
数据库问题或链接问题

**Comment by seek2024** [comment]
![Screenshot_2022_0109_015715](https://user-images.githubusercontent.com/62018857/148654575-e0c93207-68e4-41f6-a710-dc7e56a4d893.jpg)
我都可以的，可能哪里不对

**Comment by maccmspro** [comment]
数据库版本建议mysql 5.5-5.7的 重新安装一下试试
