### ISSUE TITLE
后台-基础管理-app管理-添加报错

### ISSUE THREAD

**Issue by geyoubin** [maccmspro/maccms_pro#8]
PHP版本：7.0，5.6

语法解析错误: syntax error, unexpected ''); ?></label>' (T_CONSTANT_ENCAPSED_STRING), expecting ',' or ';'

**Comment by maccmspro** [comment]
收到 我们排查下

**Comment by maccmspro** [comment]
我们试了无法复现 是否是原版文件？可以重新安装试试
如果确认问题依旧 麻烦提供具体报错的日志 哪个文件第几行

**Comment by maccmspro** [comment]
issue先关闭了 需要的话再打开吧
